### ISSUE TITLE
Separate the W and Cu poloidal surface

### ISSUE THREAD

**Issue by mougenj** [RemDelaporteMathurin/3d_monoblocks#13]
Hello
In the geometry, both W and Cu poloidal gaps are included in "poloidal_gap".
For baking simulations including recombinaison on boundary conditions, the both surface must be separated to impose different value of Kr_0 and E_Kr.

So I suggest to add in mesh_with_salome.py :

    **poloidal_gap_Cu = geompy.CreateGroup(scaled_geometry, geompy.ShapeType["FACE"])
    geompy.UnionIDs(poloidal_gap_Cu, [96])
    poloidal_gap_W = geompy.CreateGroup(scaled_geometry, geompy.ShapeType["FACE"])
    geompy.UnionIDs(poloidal_gap_W, [22])**

    **geompy.addToStudyInFather(scaled_geometry, poloidal_gap_Cu, "poloidal_gap_Cu")
    geompy.addToStudyInFather(scaled_geometry, poloidal_gap_W, "poloidal_gap_W")**

    **poloidal_gap_2 = Mesh_1.GroupOnGeom(poloidal_gap_W, "poloidal_gap_W", SMESH.FACE)
    poloidal_gap_3 = Mesh_1.GroupOnGeom(poloidal_gap_Cu, "poloidal_gap_Cu", SMESH.FACE)**

    isDone = Mesh_1.Compute()
    [
        tungsten_1,
        cu_1,
        cucrzr_1,
        top_surface_1,
        cooling_surface_1,
        poloidal_gap_1,
        **poloidal_gap_2,
        poloidal_gap_3,**
        toroidal_gap_1,
        bottom_1,
        face_top_pipe_1,
    ] = Mesh_1.GetGroups()

    **smesh.SetName(poloidal_gap_2, "poloidal_gap_W")
    smesh.SetName(poloidal_gap_3, "poloidal_gap_Cu")**

what do you think?

**Comment by RemDelaporteMathurin** [comment]
Hi, yes that would be a good addition. What are the ** characters in the salome script?

I'm afraid I don't have a lot of bandwith to do this right now.

**Comment by mougenj** [comment]
oh the **: just to make a bold police! You can ignore it!
Yes of course, there's no rush, I did it. I'm doing some tests on it.

**Comment by RemDelaporteMathurin** [comment]
oh I see okay!

Yes I remember not caring a lot about this because I was applying instantaneous recombination on everything. But if we want to investigate recomb coefficients then it's good to seperate them. Sorry for being lazy back then ;-)
